version: 2.1

orbs:
  heroku: circleci/heroku@1.0.1

jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout # special step to check out source code to working directory
      - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          keys: 
            - v1-repo-{{ checksum "package-lock.json" }}

      - run:
          name: Install dependencies with NPM
          command: npm install # replace with `yarn install` if using yarn
      - save_cache: # special step to save the dependency cache
          key: v1-repo-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run:
          name: Run tests
          # Runs jest with "--maxWorkers=2" argument to avoid OOM issues
          command: npm test # replace with `yarn test` if using yarn
      - run:
          name: Package Application
          command: |
            yarn run build --yes
            ls
            mkdir -p /tmp/app
            ls -la
            cp -R build /tmp/app
      - store_artifacts: 
          path: test-results
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: /tmp/app

workflows:
  Build and Test:
    jobs:
      - build
      - heroku/deploy-via-git:
          filters:
            branches:
              only: master
          requires:
            - build
      